services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    container_name: monero_superbrain_app_proxy
    restart: on-failure
    environment:
      - APP_HOST=monero_superbrain_dashboard
      - APP_PORT=3000
      - LOG_LEVEL=debug
      - PROXY_AUTH_ADD_HEADER_PREFIX=***
    networks:
      - default
      - umbrel_main_network

  dashboard:
    image: sirjamzalot/monero-superbrain-dashboard:v1.1.4
    container_name: monero_superbrain_dashboard
    restart: always
    environment:
      - APP_DATA_DIR=${APP_DATA_DIR:-/data}
      - APP_MONERO_NODE_IP=${APP_MONERO_NODE_IP:-monero_monerod_1}
      - APP_MONERO_RPC_PORT=${APP_MONERO_RPC_PORT:-18081}
      - APP_MONERO_ZMQ_PORT=${APP_MONERO_ZMQ_PORT:-18083}
      - APP_MONERO_RPC_USER=${APP_MONERO_RPC_USER:-monero}
      - APP_MONERO_RPC_PASS=${APP_MONERO_RPC_PASS:-monero}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - DEV_WALLET=${DEV_WALLET}
      - DEV_FEE_PERCENT=${DEV_FEE_PERCENT}
      - P2POOL_CHAIN=${P2POOL_CHAIN}
      - XMRIG_THREADS=${XMRIG_THREADS}
    networks:
      - default
      - umbrel_main_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR:-/data}:/data
      - /home/umbrel/umbrel/app-data/monero:/home/umbrel/umbrel/app-data/monero:ro

  p2pool:
    image: sirjamzalot/superbrain-p2pool:v1.2
    container_name: monero_superbrain_p2pool
    restart: always
    environment:
      - WALLET_ADDRESS=${WALLET_ADDRESS:-43sEimq64TtLoBaEzzxf7wVd4XcZPuGtNRP7zhT7WAgB3th9dvCrJMad99pZNKBRDmJXXXUxeZie7W5tsm7TWVrPHbxvins}
      - DEV_WALLET=${DEV_WALLET:-43sEimq64TtLoBaEzzxf7wVd4XcZPuGtNRP7zhT7WAgB3th9dvCrJMad99pZNKBRDmJXXXUxeZie7W5tsm7TWVrPHbxvins}
      - DEV_FEE_PERCENT=${DEV_FEE_PERCENT:-1}
      - P2POOL_CHAIN=${P2POOL_CHAIN:-mini}
      - APP_MONERO_NODE_IP=${APP_MONERO_NODE_IP:-monero_monerod_1}
      - APP_MONERO_RPC_PORT=${APP_MONERO_RPC_PORT:-18081}
      - APP_MONERO_ZMQ_PORT=${APP_MONERO_ZMQ_PORT:-18083}
      - APP_MONERO_RPC_USER=${APP_MONERO_RPC_USER:-monero}
      - APP_MONERO_RPC_PASS=${APP_MONERO_RPC_PASS:-monero}
    entrypoint: /bin/sh
    command: /data/scripts/start-p2pool.sh
    ports:
      - "3333:3333"
      - "37889:37889"
    volumes:
      - ${APP_DATA_DIR:-/data}:/data
      - /home/umbrel/umbrel/app-data/monero:/monero-app:ro
    networks:
      - default
      - umbrel_main_network

  xmrig-proxy:
    image: sirjamzalot/superbrain-proxy:v1.1
    container_name: monero_superbrain_proxy
    restart: always
    depends_on:
      - p2pool
    command: xmrig-proxy -o p2pool:3333 -u SuperbrainProxy -b 0.0.0.0:8888 --http-host 0.0.0.0 --http-port 8080 --http-access-token superbrain
    ports:
      - "8888:8888"
    volumes:
      - ${APP_DATA_DIR:-/data}/proxy:/data
    networks:
      - default

  xmrig:
    image: sirjamzalot/superbrain-xmrig:v1.1
    container_name: monero_superbrain_xmrig
    restart: always
    privileged: true
    depends_on:
      - xmrig-proxy
    environment:
      - XMRIG_THREADS=${XMRIG_THREADS:-0}
    entrypoint: /bin/sh
    command: /data/scripts/start-xmrig.sh
    volumes:
      - ${APP_DATA_DIR:-/data}:/data
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.99.99.0/24
  umbrel_main_network:
    external: true
