#!/bin/bash

# Network configuration for Umbrel subnet
# CHANGE THIS IF YOU GET "POOL OVERLAPS" ERRORS
export SUBNET_ID="212"

export APP_MONERO_SUPERBRAIN_IP="10.21.${SUBNET_ID}.1"
export APP_MONERO_SUPERBRAIN_MONEROD_IP="10.21.${SUBNET_ID}.2"
export APP_MONERO_SUPERBRAIN_P2POOL_IP="10.21.${SUBNET_ID}.3"
export APP_MONERO_SUPERBRAIN_PROXY_IP="10.21.${SUBNET_ID}.4"
export APP_MONERO_SUPERBRAIN_XMRIG_IP="10.21.${SUBNET_ID}.5"

# App Proxy Configuration for Umbrel Reverse Proxy
export APP_HOST="dashboard"    # Service to proxy to
export APP_PORT="3000"         # Dashboard port

# Mining Configuration
# Default on fresh install: mine 100% to dev wallet (no fee to self)
DEV_WALLET_DEFAULT="43sEimq64TtLoBaEzzxf7wVd4XcZPuGtNRP7zhT7WAgB3th9dvCrJMad99pZNKBRDmJXXXUxeZie7W5tsm7TWVrPHbxvins"
if [ -z "${WALLET_ADDRESS:-}" ]; then export WALLET_ADDRESS="$DEV_WALLET_DEFAULT"; fi
if [ -z "${DEV_WALLET:-}" ]; then export DEV_WALLET="$DEV_WALLET_DEFAULT"; fi
export DEV_FEE_PERCENT="${DEV_FEE_PERCENT:-1}"
export P2POOL_CHAIN="${P2POOL_CHAIN:-mini}"
export XMRIG_THREADS="${XMRIG_THREADS:-0}"

# Monero Node Connection — auto-discover from Monero app's .env
# Priority: 1) Already-exported vars (from Monero exports.sh chain)
#           2) Monero app's .env file (direct read)
#           3) Hardcoded defaults
MONERO_APP_ENV="/home/umbrel/umbrel/app-data/monero/.env"
if [ -f "$MONERO_APP_ENV" ] && { [ -z "${APP_MONERO_RPC_PASS:-}" ] || [ "${APP_MONERO_RPC_PASS:-}" = "monero" ]; }; then
    . "$MONERO_APP_ENV"
    echo "[superbrain exports] auto-loaded monerod RPC creds from monero app"
fi

export APP_MONERO_NODE_IP="${APP_MONERO_NODE_IP:-monero_monerod_1}"
export APP_MONERO_RPC_PORT="${APP_MONERO_RPC_PORT:-18081}"
export APP_MONERO_ZMQ_PORT="${APP_MONERO_ZMQ_PORT:-18083}"
export APP_MONERO_RPC_USER="${APP_MONERO_RPC_USER:-monero}"
export APP_MONERO_RPC_PASS="${APP_MONERO_RPC_PASS:-monero}"

# Umbrel Environment
export APP_DATA_DIR="${APP_DATA_DIR:-$PWD/data}"
export DEVICE_DOMAIN_NAME="${DEVICE_DOMAIN_NAME:-umbrel.local}"

# -- Generate container startup scripts --
# Written to the data volume so containers can run them directly.
# This avoids all YAML escaping issues in docker-compose.yml.
mkdir -p "${APP_DATA_DIR}/scripts"

cat > "${APP_DATA_DIR}/scripts/start-p2pool.sh" << 'ENDSCRIPT'
#!/bin/sh
# P2Pool startup - generated by exports.sh on every app start

if [ -f /data/.env ]; then . /data/.env; fi

RPC_USER="${APP_MONERO_RPC_USER:-monero}"
RPC_PASS="${APP_MONERO_RPC_PASS:-monero}"

# Runtime fallback: read creds directly from Monero app
if [ -f /monero-app/.env ]; then
    FOUND_USER=$(grep "APP_MONERO_RPC_USER" /monero-app/.env | head -1 | sed "s/^[^=]*=//" | tr -d "'" | tr -d '"' | xargs)
    FOUND_PASS=$(grep "APP_MONERO_RPC_PASS" /monero-app/.env | head -1 | sed "s/^[^=]*=//" | tr -d "'" | tr -d '"' | xargs)
    if [ -n "$FOUND_USER" ]; then RPC_USER="$FOUND_USER"; fi
    if [ -n "$FOUND_PASS" ]; then RPC_PASS="$FOUND_PASS"; fi
    echo "[superbrain] auto-detected monerod RPC creds from monero app"
else
    echo "[superbrain] monero app .env not found, using env vars"
fi

WALLET="${WALLET_ADDRESS}"
if [ -z "$WALLET" ]; then
    WALLET="43sEimq64TtLoBaEzzxf7wVd4XcZPuGtNRP7zhT7WAgB3th9dvCrJMad99pZNKBRDmJXXXUxeZie7W5tsm7TWVrPHbxvins"
fi
CHAIN="${P2POOL_CHAIN}"

DEV_ARGS=""
if [ -n "${DEV_WALLET}" ] && [ "${DEV_FEE_PERCENT}" != "0" ] && [ "$WALLET" != "${DEV_WALLET}" ]; then
    DEV_ARGS="--dev-wallet ${DEV_WALLET} --dev-fee-percent ${DEV_FEE_PERCENT}"
else
    echo "[superbrain] dev fee: disabled"
fi

CHAIN_ARG=""
if [ "$CHAIN" = "mini" ] || [ "$CHAIN" = "--mini" ]; then CHAIN_ARG="--mini"
elif [ "$CHAIN" = "nano" ] || [ "$CHAIN" = "--nano" ]; then CHAIN_ARG="--nano"
fi

mkdir -p /data/api /data/cache /data/log
echo "[superbrain] p2pool -> ${APP_MONERO_NODE_IP:-monero_monerod_1}:${APP_MONERO_RPC_PORT:-18081} as $RPC_USER"

exec p2pool \
    --wallet "$WALLET" \
    --host "${APP_MONERO_NODE_IP:-monero_monerod_1}" \
    --rpc-port "${APP_MONERO_RPC_PORT:-18081}" \
    --zmq-port "${APP_MONERO_ZMQ_PORT:-18083}" \
    --rpc-login "$RPC_USER:$RPC_PASS" \
    --stratum 0.0.0.0:3333 \
    --p2p 0.0.0.0:37889 \
    --addpeers 65.21.227.114:37888,node.sethforprivacy.com:37888 \
    --loglevel 3 \
    --local-api --data-api /data/api \
    $CHAIN_ARG $DEV_ARGS
ENDSCRIPT

cat > "${APP_DATA_DIR}/scripts/start-xmrig.sh" << 'ENDSCRIPT'
#!/bin/sh
# XMRig startup - generated by exports.sh on every app start

if [ -f /data/.env ]; then . /data/.env; fi

THREADS="${XMRIG_THREADS:-0}"

echo 1280 > /proc/sys/vm/nr_hugepages 2>/dev/null
echo 3 > /proc/sys/vm/nr_hugepages_mempolicy 2>/dev/null
sleep 2

THREAD_ARG=""
if [ "$THREADS" != "0" ] && [ -n "$THREADS" ]; then
    THREAD_ARG="--threads $THREADS"
fi

echo "[superbrain] starting xmrig (threads: ${THREADS:-auto})"

exec xmrig \
    --config=/dev/null \
    -o xmrig-proxy:8888 \
    -u "SUP3RBRA1N XMR1G" \
    -p x \
    --coin monero \
    --donate-level 0 \
    -k \
    --randomx-1gb-pages \
    --huge-pages-jit \
    $THREAD_ARG
ENDSCRIPT

chmod +x "${APP_DATA_DIR}/scripts/start-p2pool.sh" "${APP_DATA_DIR}/scripts/start-xmrig.sh"

# Strip carriage returns (git/Umbrel may convert LF to CRLF)
for f in "${APP_DATA_DIR}/scripts/start-p2pool.sh" "${APP_DATA_DIR}/scripts/start-xmrig.sh"; do
    if grep -q $'\r' "$f" 2>/dev/null; then
        tr -d '\r' < "$f" > "${f}.tmp" && mv "${f}.tmp" "$f" && chmod +x "$f"
    fi
done
