services:
  app_proxy:
    image: getumbrel/app-proxy:1.0.0
    container_name: brainchainz_monero_superstress_app_proxy
    restart: on-failure
    environment:
      - APP_HOST=brainchainz_monero_superstress_web
      - APP_PORT=4050
    networks:
      - default

  tor:
    image: getumbrel/tor:0.4.7.8
    container_name: brainchainz_monero_superstress_tor
    restart: on-failure
    command: ["-f", "/etc/tor/torrc"]
    volumes:
      - ${APP_DATA_DIR}/tor:/tmp/tor
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
    networks:
      - default

  monerod:
    image: sirjamzalot/monero-stressnet:latest
    container_name: brainchainz_monero_superstress_monerod
    restart: on-failure
    command: >-
      --testnet
      --non-interactive
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=28081
      --confirm-external-bind
      --out-peers=32
      --data-dir=/data
      --prune-blockchain
      --enable-dns-blocklist
      --no-igd
    volumes:
      - ${APP_DATA_DIR}/db:/data
    depends_on:
      - tor
    networks:
      - default

  wallet-rpc:
    image: sirjamzalot/monero-stressnet:latest
    container_name: brainchainz_monero_superstress_wallet_rpc
    restart: on-failure
    entrypoint: ["monero-wallet-rpc"]
    command: >-
      --testnet
      --daemon-address=brainchainz_monero_superstress_monerod:28081
      --wallet-dir=/home/monero/wallet
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=28083
      --disable-rpc-login
      --confirm-external-bind
      --trusted-daemon
    volumes:
      - ${APP_DATA_DIR}/wallet:/home/monero/wallet
    depends_on:
      - monerod
    networks:
      - default

  spammer-wallet-rpc:
    image: sirjamzalot/monero-stressnet:latest
    container_name: brainchainz_monero_superstress_spammer_wallet_rpc
    restart: on-failure
    entrypoint: ["monero-wallet-rpc"]
    command: >-
      --testnet
      --daemon-address=brainchainz_monero_superstress_monerod:28081
      --wallet-dir=/home/monero/spammer-wallet
      --rpc-bind-ip=0.0.0.0
      --rpc-bind-port=28084
      --disable-rpc-login
      --confirm-external-bind
      --trusted-daemon
    volumes:
      - ${APP_DATA_DIR}/spammer-wallet:/home/monero/spammer-wallet
    depends_on:
      - monerod
    networks:
      - default

  web:
    image: sirjamzalot/monero-stressnet-web:latest
    container_name: brainchainz_monero_superstress_web
    restart: on-failure
    environment:
      - PORT=4050
      - MONEROD_RPC=http://brainchainz_monero_superstress_monerod:28081
      - WALLET_RPC=http://brainchainz_monero_superstress_wallet_rpc:28083
      - SPAMMER_WALLET_RPC=http://brainchainz_monero_superstress_spammer_wallet_rpc:28084
      - MONITOR_DB_PATH=/data/monitor.db
    volumes:
      - ${APP_DATA_DIR}/monitor:/data
      - ${APP_DATA_DIR}/wallet:/wallet-files
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - monerod
      - wallet-rpc
      - spammer-wallet-rpc
    networks:
      - default
